"""initial_schema

Revision ID: 397ac97fd451
Revises: 
Create Date: 2026-03-08 02:43:11.125846

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '397ac97fd451'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('documents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('file_name', sa.String(length=500), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=True),
    sa.Column('file_mime_type', sa.String(length=100), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True),
    sa.Column('document_type', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('extracted_data',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('shipper_name', sa.String(length=500), nullable=True),
    sa.Column('shipper_address', sa.Text(), nullable=True),
    sa.Column('consignee_name', sa.String(length=500), nullable=True),
    sa.Column('consignee_address', sa.Text(), nullable=True),
    sa.Column('vessel_name', sa.String(length=255), nullable=True),
    sa.Column('voyage_number', sa.String(length=100), nullable=True),
    sa.Column('mbl_number', sa.String(length=100), nullable=True),
    sa.Column('hbl_number', sa.String(length=100), nullable=True),
    sa.Column('port_of_lading', sa.String(length=255), nullable=True),
    sa.Column('port_of_discharge', sa.String(length=255), nullable=True),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('country_of_destination', sa.String(length=100), nullable=True),
    sa.Column('incoterms', sa.String(length=50), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('total_declared_value', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('total_gross_weight', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('total_net_weight', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('weight_unit', sa.String(length=10), nullable=True),
    sa.Column('total_packages', sa.Integer(), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('invoice_number', sa.String(length=100), nullable=True),
    sa.Column('reference_numbers', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('container_numbers', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('overall_confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('extraction_model', sa.String(length=100), nullable=True),
    sa.Column('extraction_duration_ms', sa.Integer(), nullable=True),
    sa.Column('raw_ai_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('document_id')
    )
    op.create_table('extraction_fields',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extracted_data_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('field_value', sa.Text(), nullable=True),
    sa.Column('confidence_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('source_hint', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extracted_data_id'], ['extracted_data.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('extracted_data_id', 'field_name')
    )
    op.create_table('line_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('extracted_data_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=False),
    sa.Column('item_number', sa.String(length=50), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('hs_code', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=15, scale=4), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=True),
    sa.Column('net_weight', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('gross_weight', sa.Numeric(precision=15, scale=3), nullable=True),
    sa.Column('weight_unit', sa.String(length=10), nullable=True),
    sa.Column('package_count', sa.Integer(), nullable=True),
    sa.Column('package_type', sa.String(length=50), nullable=True),
    sa.Column('pallet_count', sa.Integer(), nullable=True),
    sa.Column('container_number', sa.String(length=50), nullable=True),
    sa.Column('po_number', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['extracted_data_id'], ['extracted_data.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('field_corrections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('org_id', sa.UUID(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('original_value', sa.Text(), nullable=True),
    sa.Column('corrected_value', sa.Text(), nullable=False),
    sa.Column('line_item_id', sa.UUID(), nullable=True),
    sa.Column('corrected_by', sa.String(length=255), nullable=True),
    sa.Column('corrected_at', sa.DateTime(), nullable=False),
    sa.Column('correction_reason', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['line_item_id'], ['line_items.id'], ),
    sa.ForeignKeyConstraint(['org_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('field_corrections')
    op.drop_table('line_items')
    op.drop_table('extraction_fields')
    op.drop_table('extracted_data')
    op.drop_table('documents')
    op.drop_table('organizations')
    # ### end Alembic commands ###
